# Generated by Django 4.2 on 2023-04-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0004_remove_recentorders_quantitybought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentorders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.sale'),
        ),
    ]
