# Generated by Django 4.2 on 2023-04-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0005_alter_recentorders_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentorders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recentorders',
            name='quantityBought',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='pharmacyapp.sale'),
        ),
        migrations.AlterField(
            model_name='recentorders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pharmacyapp.sale'),
        ),
        migrations.AlterField(
            model_name='recentorders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pharmacyapp.sale'),
        ),
    ]
