# Generated by Django 4.2 on 2023-04-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0006_remove_recentorders_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentorders',
            name='quantityBought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='pharmacyapp.sale'),
        ),
    ]
